name: Deploy this shit

#on:
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: "Environment to deploy to"
#        required: true
#        type: environment
#      imageName:
#        description: "Image name"
#        required: true
#        type: string
#      digest:
#        description: "Digest of the image to deploy"
#        required: true
#        type: string

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
      imageName:
        description: "Image name"
        required: true
        type: string
      digest:
        description: "Digest of the image to deploy"
        required: true
        type: string

jobs:
  deploy:
    name: "Awsome deploy job"
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.environment }}
    steps:
      - run : echo "Deploying ${{ inputs.imageName }} with digest ${{ inputs.digest }} to ${{ inputs.environment }}"
      - run : echo "${{ vars.WORKSHOP_ENV_VARIABLE }}"