on:
  workflow_call:
    inputs:
      push:
        description: "Push event"
        required: true
        type: boolean
    outputs:
      image_name:
        description: "Name of the image"
        value: ${{ steps.build-push.outputs.image_name }}
      digest:
        description: "Digest of the image"
        value: ${{ steps.build-push.outputs.digest }}




jobs:
  build:
    permissions:
      packages: write
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: build-push
        with:
          push: ${{ inputs.push }}
          tags: ghcr.io/${{ github.repository }}:latest
    outputs:
      image_name: fromJson(jobs.build.outputs.metadata)['image.name']
      digest: jobs.build.outputs.digest
