on:
  workflow_call:
    inputs:
      push:
        description: "Push event"
        required: true
        type: boolean


jobs:
  build:
    permissions:
      packages: write
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: push
          tags: ghcr.io/${{ github.repository }}:latest
