# The "display name", shown in the GitHub UI
name: Build and test

# Trigger, run on push on any branch
on:
  pull_request:


jobs:
  test: # The 'build' job
    uses: ./.github/workflows/reusable-test.yml
  lint:
    name: "Lint code"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Verify formatting
        run: |
          no_unformatted_files="$(gofmt -l $(git ls-files '*.go') | wc -l)"
          exit "$no_unformatted_files"